### ISSUE TITLE
你好，请问个问题

### ISSUE THREAD

**Issue by shaycormac** [Leifzhang/AndroidAutoTrack#52]
```
package com.kronos.plugin.thread.visitor

class ThreadAsmHelper : AsmHelper {
  
    private fun MethodInsnNode.hookExecutors() {
        when (this.owner) {
            EXECUTORS_OWNER -> {
                ThreadPoolCreator.poolList.forEach {
                    if (it.name == this.name && this.name == it.name && this.owner == it.owner) {
                        this.owner = Owner
                        this.name = it.methodName
                        this.desc = it.replaceDesc()
                    }
                }
            }
        }
    }
}
```

这一行代码
```
  if (it.name == this.name && this.name == it.name && this.owner == it.owner) {
.........
}
```
这一段判断条件中第二个是不是应该 this.desc == it.desc

第二个问题：那个ThreadPoolCreator的那个集合，我看你就写了5个元素在里面，而Executors这个类中有8个静态方法返回Executors,这样插桩后，会不会造成部分丢失。

最后一个问题：如果第三方使用自定义ThreadPool构造方法，应该也没法替换了吧。

只是我的一些想法，谢谢作者的这个demo，让我学习如何ASM插桩。

![image](https://user-images.githubusercontent.com/16019231/141734165-63af4688-97c1-45da-82fb-cfc1f00c56e7.png)

**Comment by Leifzhang** [comment]
因为这个其实是个demo  有些地方是没有完全写好的  我就只是把思路写下  看看是否可以真实的实现 到具体场景下 有很多东西还是要思考的

**Comment by shaycormac** [comment]
> 因为这个其实是个demo 有些地方是没有完全写好的 我就只是把思路写下 看看是否可以真实的实现 到具体场景下 有很多东西还是要思考的

嗯，明白了，我刚才试了跑了一下，在app里面新建几个Executors的那几个静态方法，然后运行，发现报错了，提示

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kassandra/secondplugin/thread/HuntThreadPoolExecutor;
```

我查看字节码,插桩应该是替换成功了，替换的类是在plugin中写的，也打进app中的dex中了，只是和MainActivity都在classes2.dex,咕咕噜一番，也没找到像样的解释，能厚着脸皮再请教一次，你遇到过这种情况么嘛，谢谢～

<img width="814" alt="image" src="https://user-images.githubusercontent.com/16019231/141747218-b7d8c874-6ff4-4413-8727-2f3d98616c8a.png">

**Comment by shaycormac** [comment]
> > 因为这个其实是个demo 有些地方是没有完全写好的 我就只是把思路写下 看看是否可以真实的实现 到具体场景下 有很多东西还是要思考的
> 
> 嗯，明白了，我刚才试了跑了一下，在app里面新建几个Executors的那几个静态方法，然后运行，发现报错了，提示
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kassandra/secondplugin/thread/HuntThreadPoolExecutor;
> ```
> 
> 我查看字节码,插桩应该是替换成功了，替换的类是在plugin中写的，也打进app中的dex中了，只是和MainActivity都在classes2.dex,咕咕噜一番，也没找到像样的解释，能厚着脸皮再请教一次，你遇到过这种情况么嘛，谢谢～
> 
> <img alt="image" width="814" src="https://user-images.githubusercontent.com/16019231/141747218-b7d8c874-6ff4-4413-8727-2f3d98616c8a.png">

不对，卧槽，我发现这个HuntThreadPoolExecutor右击showByte是灰色的，感觉不对劲，使用JADX反编译这个app的时候，竟然找不到这个  com.kassandra.secondplugin.thread.HuntThreadPoolExecutor 类的所在包，但是MainActivity的class字节码还有模有样的存在的😭

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/16019231/141748881-5179bcef-03c8-4248-9c08-0ff8ded9281b.png">

**Comment by Leifzhang** [comment]
https://juejin.cn/post/6844904179626934279  有兴趣好好品品这个  大概率有日志的

**Comment by shaycormac** [comment]
> https://juejin.cn/post/6844904179626934279 有兴趣好好品品这个 大概率有日志的

感谢耐心解释和指正，刚看完，其实你的掘金文章我每一篇都在认真的看，哈哈。
你说的日志几个关键词Failure to verify dex file，Invalid type descriptor我过滤日志没有找到。

但是我觉得是这个自定义的在plugin的HuntThreadPoolExecutor 类没有打进去。
我之所以这么认为有两点支撑：首先是在jadx中反编译没有找到这个类，
其次我自己在想啊，在transform过程中，仅仅是替换了目标方法的描述符、类名和类全限定符号而已，在plugin中写的这个类会在编译的时候打进app包么，这点我有点疑问。
我自己在多琢磨琢磨吧。

哎，还是自己欠缺的太多啊，后续再研究你的自动埋点、双击和lint，到时候有疑问，还希望多多指教，谢谢～

**Comment by Leifzhang** [comment]
好的   大佬

**Comment by Leifzhang** [comment]
我记得我在掘金上看过你的文章的 有兴趣可以加个微信聊聊呀  15801995859

**Comment by shaycormac** [comment]
> 我记得我在掘金上看过你的文章的 有兴趣可以加个微信聊聊呀 15801995859

掘金上我没有写过文章，你记错人了，哈哈哈哈，我上面的问题前两天解决了，是自己傻逼了，把自定义的线程池这个类写在plugin中了，所以打包一直找不到类。

我这两天在研究你的关于埋点点击事件，有一点研究了两天，没弄明白，请教一下，具体代码是关于解决lambda的
```
class AutoTrackHelper : AsmHelper {
 private fun insertLambda(node: ClassNode, method: MethodNode, field: FieldNode?) {
       ......
        instructions?.iterator()?.forEach {
            // 判断是不是代码的截止点
            if ((it.opcode >= Opcodes.IRETURN && it.opcode <= Opcodes.RETURN) || it.opcode == Opcodes.ATHROW) {
  //疑惑点
                instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
 //疑惑点
                instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
                // 获取到数据参数
                if (parentField != null) {
                    parentField.apply {
 //疑惑点
                        instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
                        instructions.insertBefore(
                                it, FieldInsnNode(Opcodes.GETFIELD, node.name, parentField.name, parentField.desc)
                        )
                    }
                } else {
                    instructions.insertBefore(it, LdcInsnNode("1234"))
                }
                instructions.insertBefore(
                        it, MethodInsnNode(
                        Opcodes.INVOKESTATIC,
                        "com/wallstreetcn/sample/ToastHelper",
                        "toast",
                        "(Ljava/lang/Object;Landroid/view/View;Ljava/lang/Object;)V",
                        false)
                )
            }
        }
    }
```

就是一个类的里面写lamda的时候，如果闭包里面没有类的成员变量，这个lambda最后会链接到一个静态内部类

```
 private static synthetic lambda$onCreate$0(Landroid/view/View;)V
    // parameter synthetic  v
   L0
    LINENUMBER 19 L0
    ALOAD 0
    ALOAD 0
    LDC "1234"
    INVOKESTATIC com/kassandra/awesomeasm/auto_track/ToastHelper.toast (Ljava/lang/Object;Landroid/view/View;Ljava/lang/Object;)V
   L1
    LINENUMBER 20 L1
    RETURN
   L2
    LOCALVARIABLE v Landroid/view/View; L0 L2 0
    MAXSTACK = 3
    MAXLOCALS = 1
```

而如果这个lambda闭包里面有类成员变量引用的话，会链接到一个普通的内部类

```
private synthetic lambda$onCreate$0(Landroid/view/View;)V
    // parameter synthetic  v
   L0
    LINENUMBER 23 L0
    ALOAD 1
    ALOAD 1
    ALOAD 0
    GETFIELD com/kassandra/awesomeasm/ThirdActivity.shayTest : Ljava/lang/String;
    INVOKESTATIC com/kassandra/awesomeasm/auto_track/ToastHelper.toast (Ljava/lang/Object;Landroid/view/View;Ljava/lang/Object;)V
   L1
    LINENUMBER 24 L1
    RETURN
   L2
    LOCALVARIABLE this Lcom/kassandra/awesomeasm/ThirdActivity; L0 L2 0
    LOCALVARIABLE v Landroid/view/View; L0 L2 1
    MAXSTACK = 3
    MAXLOCALS = 2

```

而我在研究你写的这个方法的时候，应该是仅仅过滤静态的方法的，那么insertLamda最后在操作帧栈赋值变量的时候，
给ToastHelp.toast 依次赋值三个参数的话，应该是

```
// 都是View的值
   instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
   instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
// 下面这个有疑问了，怎么能把 0这个位置的变量取出来呢，它此时也不是外部类的引用呀
  instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
                        instructions.insertBefore(
                                it, FieldInsnNode(Opcodes.GETFIELD, node.name, parentField.name, parentField.desc)
                        )
```

如果要是链接到一个普通的类，我能稍微明白一点，就是ALOAD 0 这个位置是外部类的引用，ALOAD 1这个位置是View的值，
这时候应该先取位置是1的View赋值，在找到0位置的外部类引用，从而拿到类成员的值

```
 instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 1))
   instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 1))
   // 获取到数据参数
                if (parentField != null) {
                    parentField.apply {
                        instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
                        instructions.insertBefore(
                                it, FieldInsnNode(Opcodes.GETFIELD, node.name, parentField.name, parentField.desc)
                        )
                    }
```

卡在这里，没想通，所以过来请教了😂

**Comment by Leifzhang** [comment]
静态和非静态的aload0 其实是不一样的 所以要拆开来处理  因为我学废了你懂吧

**Comment by shaycormac** [comment]
> 静态和非静态的aload0 其实是不一样的 所以要拆开来处理  因为我学废了你懂吧 

这样啊，还好问你，要不然一直在这原地打转悠了，感谢，感谢，我暂时还没废，哈哈哈

**Comment by shaycormac** [comment]
> 静态和非静态的aload0 其实是不一样的 所以要拆开来处理 因为我学废了你懂吧

哎，等等，我上面说的是不是太啰嗦了，重点我想表达的是静态的aload0操纵的是View变量，而非静态的aload0操纵的是类的引用this。而Demo中的Plugin的lambda中又过滤掉了非静态的，那么此时aload0操纵的肯定是View。
但是在代码中，我发现这一行

```
if (parentField != null) {
                    parentField.apply {
                        instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
                        instructions.insertBefore(
                                it, FieldInsnNode(Opcodes.GETFIELD, node.name, parentField.name, parentField.desc)
                        )
                    }
```

这不是拿View的引用来取外部类上面的我们感兴趣的那个注解@Test么，肯定是取不到的吧，因为相当于在View的类中有这个成员了，为了验证我的想法，我准备跑demo看一下，结果发现MainActivity中没有使用lambda,于是我在上面写了一个lambda的click

```
 findViewById(R.id.textView1).setOnClickListener( view->{
            
        });
```

这个lambda的链接肯定是个静态的了，所以会被插桩，我一运行，就报错了

```
 java.lang.VerifyError: Verifier rejected class com.wallstreetcn.sample.MainActivity: void com.wallstreetcn.sample.MainActivity.lambda$onCreate$1(android.view.View) failed to verify: void com.wallstreetcn.sample.MainActivity.lambda$onCreate$1(android.view.View): [0x0] cannot access instance field com.wallstreetcn.sample.Entity com.wallstreetcn.sample.MainActivity.mdata from object of type Reference: android.view.View (declaration of 'com.wallstreetcn.sample.MainActivity' appears in /data/data/com.wallstreetcn.sample/code_cache/.overlay/base.apk/classes3.dex)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
     .......
```

然后，我只是添加了一行代码，即那个类成员，放入闭包中
```
public class MainActivity extends AppCompatActivity implements View.OnClickListener {
 @Test
    private Entity mdata = new Entity();

 @Override
    protected void onCreate(Bundle savedInstanceState) {
findViewById(R.id.textView1).setOnClickListener( view->{
     // 加了这行，
            mdata.getTest();
        });
}
```
这样，它就变成了一个非静态的内部类，但是没法插桩了。😆

所以我在想，不一定对啊，是不是静态的lambda就没法插入这个类的成员,因为静态内部类里面没有外部类的引用。
但是非静态的呢，能不能抢救一下？所以呢，我在demo的plugin中修改了逻辑为储存非静态的lambda,以及代码插桩的位置aload修改了一下。

  这俩地方改成aload改成1，拿到View的值

```

               instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 1))
                instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 1))
if (parentField != null) {
                    parentField.apply {
                        instructions.insertBefore(it, VarInsnNode(Opcodes.ALOAD, 0))
                        instructions.insertBefore(
                                it, FieldInsnNode(Opcodes.GETFIELD, node.name, parentField.name, parentField.desc)
                        )
                    }
```

然后再次验证非静态的lambda

```
public class MainActivity extends AppCompatActivity implements View.OnClickListener {
 @Test
    private Entity mdata = new Entity();

 @Override
    protected void onCreate(Bundle savedInstanceState) {
findViewById(R.id.textView1).setOnClickListener( view->{
 // 加了这行，
            mdata.getTest();
        });
}
```

是可以的，弹出了预期的吐司。


**总结就是我用demo跑lambda,静态的报错，非静态没插桩。
修改了一下，静态的不处理，非静态的能拿到，但好像没解决什么问题，卧槽。**

_题外话，kotlin中引用Java的单方法接口，也就是装逼说法SAM,那么不论闭包里是否引用类成员变量，最后都是生成的静态链接，区别是引用成员变量的那种会把第一个参数作为外部类的类型，这和Ja v a里的还不一样哎！_

闭包引用成员
```
class SecondActivity : AppCompatActivity() {

    private var testCount: Int = 15

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
       
        setContentView(R.layout.activity_second)
        val button = findViewById<Button>(R.id.btn_second)
        button.setOnClickListener {

            ToastHelper.toast(it, it, testCount)
        }
    }
}


// access flags 0x1A
  private final static onCreate$lambda-0(Lcom/kassandra/awesomeasm/SecondActivity;Landroid/view/View;)V
   L0
    ALOAD 0
    LDC "this$0"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullParameter (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 20 L1
    ALOAD 1
    ALOAD 1
    ALOAD 0
    GETFIELD com/kassandra/awesomeasm/SecondActivity.testCount : I
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    INVOKESTATIC com/kassandra/awesomeasm/auto_track/ToastHelper.toast (Ljava/lang/Object;Landroid/view/View;Ljava/lang/Object;)V
   L2
    LINENUMBER 21 L2
    RETURN
   L3
    LOCALVARIABLE this$0 Lcom/kassandra/awesomeasm/SecondActivity; L0 L3 0
    LOCALVARIABLE it Landroid/view/View; L0 L3 1
    MAXSTACK = 3
    MAXLOCALS = 2



```

闭包不引用成员
```
class SecondActivity : AppCompatActivity() {

  
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
       
        setContentView(R.layout.activity_second)
        val button = findViewById<Button>(R.id.btn_second)
        button.setOnClickListener {

            ToastHelper.toast(it, it, "fuck")
        }
    }
}


 // access flags 0x1A
  private final static onCreate$lambda-0(Landroid/view/View;)V
   L0
    LINENUMBER 20 L0
    ALOAD 0
    ALOAD 0
    LDC "fuck"
    INVOKESTATIC com/kassandra/awesomeasm/auto_track/ToastHelper.toast (Ljava/lang/Object;Landroid/view/View;Ljava/lang/Object;)V
   L1
    LINENUMBER 21 L1
    RETURN
   L2
    LOCALVARIABLE it Landroid/view/View; L0 L2 0
    MAXSTACK = 3
    MAXLOCALS = 1
```

和java不一样啊，Fuck～

**Comment by Leifzhang** [comment]
恩  这种感觉都具体问题具体分析 应该是都能搞定的

**Comment by shaycormac** [comment]
> 恩 这种感觉都具体问题具体分析 应该是都能搞定的

双击lambda处理这块，目前我的实践是,它的动态链接指向的内部方法不论是静态还是普通的，我主要看这个MethodNode中有几个参数，如果是1个的话，说明肯定是lambda闭包里没有引用类成员，从而这种lambda是无法插桩的，如果大于等于2个，表明是Java的lambda引用类成员从而指向内部普通方法或者kotlin的lambda引用类成员从而指向内部静态方法，但它第一个参数是当前的类引用，这种参数大于2个的都可以正常插桩。
埋点获取外部类lambda处理和这个逻辑一样，大于2个参数的都能正常插入，单个参数就无法处理了。
我回头再说埋点的匿名内部类遇到的蛋疼问题。
